-- GERADO por scripts/gen-seed.mjs — não editar à mão.
-- Idempotente: pode rodar de novo (upsert nos jogos, admin garantido).

insert into public.allowlist (email, role) values ('gabriel.fernandeshw@gmail.com', 'admin')
  on conflict (email) do update set role = 'admin';

insert into public.games (id, title, console, year, youtube_id, pitch, series, series_order, wiki_title) values
  ('chrono-trigger', 'Chrono Trigger', 'SNES', 1995, '8USTC91ckaQ', 'O RPG que quase todo mundo cita como o melhor de todos os tempos.', 'chrono', 1, 'Chrono Trigger'),
  ('chrono-cross', 'Chrono Cross', 'PS1', 1999, 'U709nJ_AQ-s', 'Sucessor ambicioso com uma das trilhas sonoras mais bonitas já compostas.', 'chrono', 2, 'Chrono Cross'),
  ('zelda-alttp', 'The Legend of Zelda: A Link to the Past', 'SNES', 1991, 'ZsexNXltd2Y', 'O molde de todo Zelda que veio depois — aventura top-down impecável.', null, null, 'The Legend of Zelda: A Link to the Past'),
  ('zelda-oot', 'The Legend of Zelda: Ocarina of Time', 'N64', 1998, 'GwKLbjfjpZM', 'Frequentemente eleito o melhor jogo já feito, sem ironia.', null, null, 'The Legend of Zelda: Ocarina of Time'),
  ('zelda-mm', 'The Legend of Zelda: Majora''s Mask', 'N64', 2000, 'AAbKdyUDDfc', 'Ciclo de três dias, tom sombrio e a ideia mais ousada da série.', null, null, 'The Legend of Zelda: Majora''s Mask'),
  ('zelda-la', 'The Legend of Zelda: Link''s Awakening DX', 'GBC', 1998, 'oR46QVM9bcQ', 'Zelda portátil surreal, afetivo e inesquecível.', null, null, 'The Legend of Zelda: Link''s Awakening'),
  ('zelda-minish', 'The Legend of Zelda: The Minish Cap', 'GBA', 2004, '0hTrom_OtfE', 'Link encolhe ao tamanho de um inseto — o Zelda portátil mais charmoso.', null, null, 'The Legend of Zelda: The Minish Cap'),
  ('zelda-ages', 'The Legend of Zelda: Oracle of Ages', 'GBC', 2001, 'TCWgLBR_N-A', 'Zelda de viagem no tempo, feito pela Capcom, com puzzle pesado.', null, null, 'The Legend of Zelda: Oracle of Ages and Oracle of Seasons'),
  ('ff6', 'Final Fantasy VI', 'SNES', 1994, 'j_lr12kgGeU', 'Elenco enorme, o vilão mais lembrado da série e uma ópera no meio do jogo.', null, null, 'Final Fantasy VI'),
  ('ff7', 'Final Fantasy VII', 'PS1', 1997, 'MMOHD0B0BJU', 'O RPG que levou o gênero ao mainstream do mundo inteiro.', null, null, 'Final Fantasy VII'),
  ('ff8', 'Final Fantasy VIII', 'PS1', 1999, 'h9e7wdCVPcs', 'Jovem, estiloso e polêmico — o FF que dividiu os fãs e marcou época.', null, null, 'Final Fantasy VIII'),
  ('ff9', 'Final Fantasy IX', 'PS1', 2000, 'iUQMWeFsY8w', 'Volta às raízes de fantasia medieval — o favorito de muito fã raiz.', null, null, 'Final Fantasy IX'),
  ('fft', 'Final Fantasy Tactics', 'PS1', 1997, 'Q0xm3Oteai8', 'Tático sombrio com roteiro de intriga política digno de romance.', null, null, 'Final Fantasy Tactics'),
  ('tactics-ogre', 'Tactics Ogre: Let Us Cling Together', 'PS1', 1997, 'ayhks2FuKqY', 'Tático sobre limpeza étnica e escolhas sem volta — a base de Final Fantasy Tactics.', null, null, 'Tactics Ogre: Let Us Cling Together'),
  ('super-metroid', 'Super Metroid', 'SNES', 1994, '87jXoj-4C5U', 'A aula definitiva de level design, atmosfera e exploração.', 'metroid', 1, 'Super Metroid'),
  ('metroid-fusion', 'Metroid Fusion', 'GBA', 2002, 'kiq4eOUDI2k', 'Samus acuada, guiada e caçada — o Metroid mais linear e tenso.', 'metroid', 2, 'Metroid Fusion'),
  ('metroid-zm', 'Metroid: Zero Mission', 'GBA', 2004, 'xjMan14CFeE', 'Releitura enxuta e brilhante do Metroid original.', null, null, 'Metroid: Zero Mission'),
  ('sotn', 'Castlevania: Symphony of the Night', 'PS1', 1997, 'mG6-3Dthsy0', 'Fundou o ''metroidvania'' como a gente conhece hoje.', null, null, 'Castlevania: Symphony of the Night'),
  ('castlevania-aos', 'Castlevania: Aria of Sorrow', 'GBA', 2003, 'ZNCfiBDjUhY', 'Metroidvania portátil no auge — roube a alma de cada inimigo.', null, null, 'Castlevania: Aria of Sorrow'),
  ('secret-of-mana', 'Secret of Mana', 'SNES', 1993, 'CTrawcuaHUM', 'Action-RPG com co-op local que virou lenda entre amigos.', null, null, 'Secret of Mana'),
  ('earthbound', 'EarthBound', 'SNES', 1994, '-knEvpvmlAI', 'Estranho, engraçado e décadas à frente do seu tempo.', 'mother', 1, 'EarthBound'),
  ('mother3', 'Mother 3', 'GBA', 2006, 'sScHQrPJ4FU', 'Sequência de EarthBound: engraçada, e aí de repente devastadora.', 'mother', 2, 'Mother 3'),
  ('terranigma', 'Terranigma', 'SNES', 1995, '1f_vEnlrqyk', 'Action-RPG cult sobre ressuscitar o mundo, peça por peça.', null, null, 'Terranigma'),
  ('illusion-of-gaia', 'Illusion of Gaia', 'SNES', 1994, 'o0yB3LJTqNU', 'Aventura sombria e melancólica sobre crescer no meio do apocalipse.', null, null, 'Illusion of Gaia'),
  ('lufia2', 'Lufia II: Rise of the Sinistrals', 'SNES', 1995, 'WsfZkOIHztU', 'JRPG cheio de puzzles com uma abertura que já entrega o final. Cult absoluto.', null, null, 'Lufia II: Rise of the Sinistrals'),
  ('mgs1', 'Metal Gear Solid', 'PS1', 1998, 'U3CZK-hO6lM', 'Stealth cinematográfico que redefiniu o que narrativa em game podia ser.', null, null, 'Metal Gear Solid (video game)'),
  ('re1', 'Resident Evil', 'PS1', 1996, 'UeyBz1mhPQ4', 'O jogo que fundou o survival horror e aterrorizou uma geração.', 're', 1, 'Resident Evil (1996 video game)'),
  ('re2', 'Resident Evil 2', 'PS1', 1998, 'PcDjo_uKeF4', 'O ápice do survival horror clássico, com dois cenários entrelaçados.', 're', 2, 'Resident Evil 2 (1998 video game)'),
  ('re3', 'Resident Evil 3: Nemesis', 'PS1', 1999, 'DAB1YPlwiB4', 'Raccoon City em chamas e um perseguidor que nunca para.', 're', 3, 'Resident Evil 3: Nemesis'),
  ('silent-hill', 'Silent Hill', 'PS1', 1999, '_5mZKe40zDA', 'Terror psicológico que ainda assombra quem jogou.', null, null, 'Silent Hill (video game)'),
  ('dino-crisis', 'Dino Crisis', 'PS1', 1999, 'LV2IuPD8TmI', 'Resident Evil com dinossauros, feito pelo mesmo time. Tenso do início ao fim.', null, null, 'Dino Crisis (video game)'),
  ('parasite-eve', 'Parasite Eve', 'PS1', 1998, '9FBb4DuEmFw', 'Survival horror com RPG numa Nova York de pesadelo.', 'pe', 1, 'Parasite Eve (video game)'),
  ('parasite-eve-2', 'Parasite Eve II', 'PS1', 1999, 'Ac-eFW3s-nA', 'Menos RPG, mais ação — survival horror puro.', 'pe', 2, 'Parasite Eve II'),
  ('xenogears', 'Xenogears', 'PS1', 1998, 'FT2Q10vNoPE', 'RPG filosófico, denso e profundamente cultuado.', null, null, 'Xenogears'),
  ('vagrant-story', 'Vagrant Story', 'PS1', 2000, 'lBvFP2SIzhk', 'Ação-RPG sombrio com uma profundidade de sistemas quase absurda.', null, null, 'Vagrant Story'),
  ('grandia', 'Grandia', 'PS1', 1997, 'YB7JEtniTd0', 'Sistema de batalha ainda copiado hoje; aventura leve e carismática.', null, null, 'Grandia (video game)'),
  ('legend-dragoon', 'The Legend of Dragoon', 'PS1', 1999, 'utSIYd0vl5I', 'Épico de quatro CDs com batalhas de timing. Cult declarado no Brasil.', null, null, 'The Legend of Dragoon'),
  ('wild-arms', 'Wild Arms', 'PS1', 1996, 'JvQaqDWoxt4', 'Faroeste com magia e robôs — o primeiro RPG 3D do PlayStation.', null, null, 'Wild Arms (video game)'),
  ('lunar-sssc', 'Lunar: Silver Star Story Complete', 'PS1', 1998, '92tSSdoLaks', 'Jornada clássica de herói com cutscenes animadas e nenhuma dificuldade punitiva.', null, null, 'Lunar: Silver Star Story Complete'),
  ('suikoden1', 'Suikoden', 'PS1', 1996, 'WzLvvv5t0tE', 'Início da saga: 108 Estrelas do Destino, um exército e um castelo pra reconstruir.', 'suikoden', 1, 'Suikoden (video game)'),
  ('suikoden2', 'Suikoden II', 'PS1', 1998, 'rfAJ5a6V7KI', 'Guerra, política e um dos melhores vilões dos games.', 'suikoden', 2, 'Suikoden II'),
  ('tomb-raider', 'Tomb Raider', 'PS1', 1996, 'VkD8x9aItCs', 'Lara Croft, tumbas milenares e puzzles — a aventura que definiu o gênero.', null, null, 'Tomb Raider (1996 video game)'),
  ('golden-sun', 'Golden Sun', 'GBA', 2001, 'XYFJCXcdhb0', 'RPG portátil com puzzles de Psinergia e visual de impressionar na época.', 'golden-sun', 1, 'Golden Sun (video game)'),
  ('golden-sun-2', 'Golden Sun: The Lost Age', 'GBA', 2003, 'R7UpzDGS7b4', 'A outra metade da história — agora do lado de quem parecia vilão.', 'golden-sun', 2, 'Golden Sun: The Lost Age'),
  ('pokemon-emerald', 'Pokémon Emerald', 'GBA', 2004, 'KInoJimjJzI', 'Para muita gente, a definição de ''modo história'' de Pokémon.', null, null, 'Pokémon Emerald'),
  ('pokemon-crystal', 'Pokémon Crystal', 'GBC', 2000, 'FUkAmzhXOZo', 'A versão definitiva da gen 2 — Johto, Kanto e o Suicune com história própria.', null, null, 'Pokémon Crystal'),
  ('phantasy-star-4', 'Phantasy Star IV', 'MD', 1993, '2ieD0rPFbAk', 'O auge do RPG 16-bit e o fecho perfeito de uma saga inteira.', null, null, 'Phantasy Star IV: The End of the Millennium'),
  ('shining-force-2', 'Shining Force II', 'MD', 1994, 'CwUNky1N4PY', 'Tático acessível e viciante — o melhor lugar pra começar em Shining Force.', null, null, 'Shining Force II'),
  ('fire-emblem', 'Fire Emblem', 'GBA', 2003, 'ALuRb6UqTKU', 'O tático que apresentou a série ao Ocidente — permadeath e roteiro denso.', null, null, 'Fire Emblem: The Blazing Blade')
on conflict (id) do update set
  title = excluded.title, console = excluded.console, year = excluded.year,
  youtube_id = excluded.youtube_id, pitch = excluded.pitch,
  series = excluded.series, series_order = excluded.series_order,
  wiki_title = excluded.wiki_title;
